CREATE INDEX "IDX_46a85229c9953b2b94f768190b" ON public.categories USING btree ("tenantId");
CREATE INDEX "IDX_beta_keys_used" ON public.beta_keys USING btree ("isUsed");
CREATE INDEX "IDX_cash_movements_cashRegisterId" ON public.cash_movements USING btree ("cashRegisterId");
CREATE INDEX "IDX_cash_movements_createdAt" ON public.cash_movements USING btree ("createdAt");
CREATE INDEX "IDX_cash_movements_type" ON public.cash_movements USING btree (type);
CREATE INDEX "IDX_customer_credits_customerId" ON public.customer_credits USING btree ("customerId");
CREATE INDEX "IDX_customer_credits_dueDate" ON public.customer_credits USING btree ("dueDate");
CREATE INDEX "IDX_customer_credits_reference" ON public.customer_credits USING btree ("referenceType", "referenceId");
CREATE INDEX "IDX_customer_credits_status" ON public.customer_credits USING btree (status);
CREATE INDEX "IDX_customer_credits_type" ON public.customer_credits USING btree (type);
CREATE INDEX "IDX_customers_tenantId" ON public.customers USING btree ("tenantId");
CREATE INDEX "IDX_dian_resolutions_tenant" ON public.dian_resolutions USING btree ("tenantId");
CREATE INDEX "IDX_expenses_status" ON public.expenses USING btree (status);
CREATE INDEX "IDX_expenses_tenantId_expenseDate" ON public.expenses USING btree ("tenantId", "expenseDate");
CREATE INDEX "IDX_inventory_movements_productId" ON public.inventory_movements USING btree ("productId");
CREATE INDEX "IDX_inventory_movements_reference" ON public.inventory_movements USING btree ("referenceType", "referenceId");
CREATE INDEX "IDX_inventory_movements_tenantId" ON public.inventory_movements USING btree ("tenantId");
CREATE INDEX "IDX_inventory_movements_warehouseId" ON public.inventory_movements USING btree ("warehouseId");
CREATE INDEX "IDX_inventory_stock_productId" ON public.inventory_stock USING btree ("productId");
CREATE INDEX "IDX_inventory_stock_productVariantId" ON public.inventory_stock USING btree ("productVariantId");
CREATE INDEX "IDX_inventory_stock_status" ON public.inventory_stock USING btree (status);
CREATE INDEX "IDX_inventory_stock_tenantId" ON public.inventory_stock USING btree ("tenantId");
CREATE INDEX "IDX_inventory_stock_warehouseId" ON public.inventory_stock USING btree ("warehouseId");
CREATE INDEX "IDX_otp_email" ON public.otp_codes USING btree (email);
CREATE INDEX "IDX_otp_expires" ON public.otp_codes USING btree ("expiresAt");
CREATE INDEX "IDX_payments_processedById" ON public.payments USING btree ("processedById");
CREATE INDEX "IDX_payments_saleId" ON public.payments USING btree ("saleId");
CREATE INDEX "IDX_sale_items_saleId_productId" ON public.sale_items USING btree ("saleId", "productId");
CREATE INDEX "IDX_taxes_name" ON public.taxes USING btree (name);
CREATE INDEX "IDX_users_tenant" ON public.users USING btree ("tenantId");
CREATE INDEX idx_chart_tenant ON public.chart_of_accounts USING btree ("tenantId");
CREATE INDEX idx_chart_tenant_active ON public.chart_of_accounts USING btree ("tenantId", "isActive");
CREATE INDEX idx_journal_reference ON public.journal_entries USING btree ("referenceId", "referenceType");
CREATE INDEX idx_journal_tenant ON public.journal_entries USING btree ("tenantId");
CREATE INDEX idx_journal_tenant_date ON public.journal_entries USING btree ("tenantId", "entryDate");
CREATE INDEX idx_journal_tenant_status ON public.journal_entries USING btree ("tenantId", status);
CREATE INDEX idx_journal_tenant_type ON public.journal_entries USING btree ("tenantId", type);
CREATE INDEX idx_line_account ON public.journal_entry_lines USING btree ("accountId");
CREATE INDEX idx_line_journal ON public.journal_entry_lines USING btree ("journalEntryId");
CREATE INDEX idx_withhold_cert ON public.tax_withholdings USING btree ("certificateNumber");
CREATE INDEX idx_withhold_tenant ON public.tax_withholdings USING btree ("tenantId");
CREATE INDEX idx_withhold_tenant_date ON public.tax_withholdings USING btree ("tenantId", "withholdingDate");
CREATE INDEX idx_withhold_tenant_direction ON public.tax_withholdings USING btree ("tenantId", direction);
CREATE INDEX idx_withhold_tenant_type ON public.tax_withholdings USING btree ("tenantId", type);